### ISSUE TITLE
Add API documentation on one of the usual doc sites

### ISSUE THREAD

**Issue by andy-maier** [workhorsylegacy/py-osinfo#10]
My recommendation for that would be:
- Google style docstrings as the source
- Sphinx with the autodoc and napoleon extensions to process them
- Host it on ReadTheDocs
- Have a target in the makefile to build the HTML docs locally

**Comment by workhorsy** [comment]
Thanks for the bug report.

Py-osinfo is still in the experimental stages. It has a few design problems that when fixed, will probably fundamentally change the way it works from an API stand point. I would like to fix those things before making API documentation.

This bug will have to be put on hold until later.

**Comment by workhorsy** [comment]
Closing this for now as the project is deprecated.
