### ISSUE TITLE
Not clear whether brand is machine readable or for humans

### ISSUE THREAD

**Issue by andy-maier** [workhorsylegacy/py-osinfo#11]
My take on that is to declare it a machine readable value, that stays the same across OS releases.

The ID values returned by the `distro` package provide that for Linux, and guarantee that the values don't change (it has a normalization support built in).

As a positive side effect, this would allow getting rid of the long list of Linux distros in `osinfo`, and to just use the `distro.id()` value.

The downside is that the `osinfo` Linux brand strings will change (once), compared to now.

**Comment by andy-maier** [comment]
The Linux code in `_get_os_brand()` would get reduced to: 

    elif os_type in OSType.Linux:
        return distro.id()

**Comment by workhorsy** [comment]
Closing this for now as the project is deprecated.
