### ISSUE TITLE
platform.linux_distribution() and platform.dist() will go away

### ISSUE THREAD

**Issue by andy-maier** [workhorsylegacy/py-osinfo#9]
I'd like to point out that the Python core community has deprecated `platform.linux_distribution()` in Python 3.5 and `platform.linux_dist()` already in Python 2.6, and plans to remove both of them in Python 3.7.

Also, these functions have a number of issues.

See [Python issue 1322](https://bugs.python.org/issue1322) for more information.

As part of that discussion, the `ld` project emerged with the goal to provide a richer and more accurate alternative to these two functions. It is meanwhile called `distro` and is available on [PyPI](https://pypi.python.org/pypi/distro) and its API documentation is on [RTD](http://distro.readthedocs.org/en/latest/). As of its v0.6.0, it is fairly complete.

I think your `osinfo` package does a great job in providing cross-platform information about the OS, with its concept of `type` and `brand`, and I was wondering whether for Linux, you could consider using the `distro` package instead of the deprecated platform functions?

**Comment by workhorsy** [comment]
Interesting. I was just dealing with platform.dist being deprecated on another project a few hours ago.

This distro module looks very interesting. However I'm a bit conflicted about having an external dependency. I'm also interested in how it deals with all the distros that are based on debian/ubuntu/centos and don't "do the right thing" of changing the name in the lsb-release and os-release files.

I'll have to investigate this issue and look more into how that module works: https://github.com/nir0s/distro/issues/109

**Comment by workhorsy** [comment]
Closing this for now as the project is deprecated.
